### ISSUE TITLE
JanusGraph class and buildTransaction method

### ISSUE THREAD

**Issue by Nasoki-Koide** [JanusGraph/janusgraph-dotnet#143]
In Java version of JanusGraph, there is JanusGraph.buildTransaction() method. I' m using C# and I would like to use that to configure transaction to readonly mode. But, there is no corresponding class and method in janusgraph-dotnet. Could you add them?

**Comment by FlorianHockmann** [comment]
`buildTransaction()` is part of the JanusGraph graph API which is not available to a remote client like JanusGraph.Net. You can however configure options like that in your JanusGraph Server that you connect to from JanusGraph.Net. So, you could easily create JanusGraph Server instances as readonly and others as non-readonly. Then you can connect to the instances based on whether you want to allow modifications or not.

I'm closing this now as it's not planned to implement the graph API in JanusGraph.Net. If you have any further questions, please head to one of [JanusGraph's community channels](https://github.com/JanusGraph/janusgraph#community).

**Comment by Nasoki-Koide** [comment]
@FlorianHockmann  Thank you very much for your answer. Alright, I'll change the configuration of server.
