### ISSUE TITLE
Support JanusGraph 0.6

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph-dotnet#59]
This includes:

- [ ]  Internal breaking changes of the GraphSON serialization for JanusGraph predicates.
- [x] Update Gremlin.Net to version 3.5.0.

**Comment by FlorianHockmann** [comment]
I updated the issue as JanusGraph 0.6.0 is now right around the corner so that we don't have to prepare JanusGraph.Net for it but we can directly support it.
